### ISSUE TITLE
[Error] async/await is not yet supported in Client Components

### ISSUE THREAD

**Issue by junni01kim** [Daou-FiveGuys/fiveguys_frontend#49]
**버그 설명**
프리캡스톤 프론트에서 Google Login을 진입할 시, 해당 컴포넌트가 use client 설정이 되어있지 않은 채 API 호출(async/await)을 시도하여 생기는 버그로 추정

**버그 생성 조건**
1. 프론트, 백 서버 개설
2. 프론트 페이지 /login 접속*버그 설명**
프리캡스톤 프론트에서 Google Login을 진입할 시, 해당 컴포넌트가 use client 설정이 되어있지 않은 채 API 호출(async/await)을 시도하여 생기는 버그로 추정

**버그 생성 조건**
1. 프론트, 백 서버 개설
2. 프론트 페이지 [/login ](http://hansung-fiveguys.duckdns.org/login) 접속
3. `Google로 로그인` 클릭
4. 개인 계정으로 로그인
5. 리다이렉션 후 에러발생

**정상적인 상황**
![image](https://github.com/user-attachments/assets/9a3fb776-5be3-48e9-9442-264d737eac68)
이후

![image](https://github.com/user-attachments/assets/fd5d75df-8f85-4308-a14b-1b9b1fd2e985)
해당 장면처럼 구글 페이지로 이동해야함.

**버그 화면**
![image](https://github.com/user-attachments/assets/3ee78817-305e-4e88-87cf-e3d8bbb5e117)
현재는 챗봇화면으로 이동되지 않음

**테스트 기종(please complete the following information):**
 - OS: Windows, Linux
 - Browser: Chrome
 - Version: 가장 최신 main 커밋(399d2ef)

**추가 설명**

**Comment by 6-keem** [comment]
해결
