### ISSUE TITLE
문자 발송 기록 오류 발생

### ISSUE THREAD

**Issue by junni01kim** [Daou-FiveGuys/fiveguys_frontend#90]
**버그 설명**
이미지를 전송하지 않은 문자 기록에 이미지 출력.
1. 뿌리오 문자 발송 타입 중, 이미지가 아닌 메세지만 발송하는 타입(SMS, LMS)의 경우 DB에 이미지 정보가 저장되지 않는다. 즉 해당 타입의 경우 fiveguys_backend의 message_history.sendImage가 Null이다.
2. 하지만 현재 프론트는 해당 타입의 경우에도 sendImage의 값을 출력하고, 그 결과 깨진 이미지가 페이지에 출력되게 된다.

**버그 생성 조건**
버그 발생 과정 재현  
1. SMS 혹은 LMS 타입의 메세지를 발송
2. 메세지 전송 기록 페이지 이동
3. 해당 문자 기록 확인

**정상적인 상황**
![image](https://github.com/user-attachments/assets/cbe3d3ec-651c-4228-8700-2942bd1f66f5)
message_history.sendImage에 이미지가 존재하는 기록(MMS타입의 메세지 기록)의 경우

**버그 화면**
![image](https://github.com/user-attachments/assets/c5d2f217-0c8f-413c-9eb8-6ca69a6efe46)
message_history.sendImage에 이미지가 존재하지 않는 기록(SMS, LMS 타입의 메세지 기록)의 경우

**테스트 기종(please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: main branch [c035a48](https://github.com/Daou-FiveGuys/fiveguys_frontend/commit/c035a4861848c011feab31fb8b542d0eee2bfdd6)

**추가 설명**
반환 타입이 MMS가 아닌경우, sendImage를 출력하지 않으면 해결될 것으로 판단

**Comment by 6-keem** [comment]
[Resloved] 
원인 : null checking을 문자열로 하였음 ( === 'null' )
