### ISSUE TITLE
[주소록] : 연락처 추가 오류

### ISSUE THREAD

**Issue by 6-keem** [Daou-FiveGuys/fiveguys_frontend#93]
<img width="1490" alt="스크린샷 2024-11-25 15 54 43" src="https://github.com/user-attachments/assets/f608fb54-34c6-4149-946a-77fa31514128">

<img width="715" alt="image" src="https://github.com/user-attachments/assets/c2dba6f0-7f6e-4c8e-87fc-c1cae950cd4d">

연락처 추가 시 오류 발생

**Comment by junni01kim** [comment]
추가 조사결과 이미 존재하는 그룹에 연락처를 추가하는 경우 정상작동합니다.
빠른 시일내에 수정하겠습니다.

**Comment by junni01kim** [comment]
해결 완료 [d89e1d1](https://github.com/Daou-FiveGuys/fiveguys_frontend/commit/d89e1d1342121438d29652484fc383f95bdef91b) 참고
